"""users sessions and login limits

Revision ID: 0002_auth
Revises: 0001_initial
Create Date: 2026-09-29 17:20:44.879675

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_auth"
down_revision: str | Sequence[str] | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_limits",
        sa.Column("key", sa.String(length=67), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_login_limits")),
    )
    op.create_index(
        op.f("ix_login_limits_expires_at"), "login_limits", ["expires_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "is_emergency",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "must_change_password",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "ui_language", sa.String(length=2), server_default="en", nullable=False
        ),
        sa.Column(
            "note_naming", sa.String(length=7), server_default="letters", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "note_naming IN ('letters', 'solfege')", name=op.f("ck_users_note_naming")
        ),
        sa.CheckConstraint(
            "role IN ('manager', 'student')", name=op.f("ck_users_role")
        ),
        sa.CheckConstraint(
            "ui_language IN ('ru', 'en', 'es')", name=op.f("ck_users_ui_language")
        ),
        sa.CheckConstraint(
            "username = lower(username)", name=op.f("ck_users_canonical_username")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_index(
        "uq_users_emergency",
        "users",
        ["is_emergency"],
        unique=True,
        postgresql_where=sa.text("is_emergency"),
    )
    op.create_table(
        "login_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("csrf_token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_login_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_login_sessions")),
    )
    op.create_index(
        op.f("ix_login_sessions_expires_at"),
        "login_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_login_sessions_user_id"), "login_sessions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_login_sessions_user_id"), table_name="login_sessions")
    op.drop_index(op.f("ix_login_sessions_expires_at"), table_name="login_sessions")
    op.drop_table("login_sessions")
    op.drop_index(
        "uq_users_emergency",
        table_name="users",
        postgresql_where=sa.text("is_emergency"),
    )
    op.drop_table("users")
    op.drop_index(op.f("ix_login_limits_expires_at"), table_name="login_limits")
    op.drop_table("login_limits")
    # ### end Alembic commands ###
