"""exercises and protected media

Revision ID: 0003_exercises
Revises: 0002_auth
Create Date: 2026-09-29 19:43:03.922863

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_exercises"
down_revision: str | Sequence[str] | None = "0002_auth"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_files",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=50), nullable=False),
        sa.Column("mime_type", sa.String(length=50), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds > 0",
            name=op.f("ck_media_files_duration"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_media_files_size")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_files")),
        sa.UniqueConstraint("filename", name=op.f("uq_media_files_filename")),
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.String(length=36), nullable=True),
        sa.Column("audio_id", sa.String(length=36), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "image_id IS NOT NULL OR audio_id IS NOT NULL",
            name=op.f("ck_exercises_media_required"),
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_exercises_position")),
        sa.ForeignKeyConstraint(
            ["audio_id"],
            ["media_files.id"],
            name=op.f("fk_exercises_audio_id_media_files"),
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["media_files.id"],
            name=op.f("fk_exercises_image_id_media_files"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercises")),
    )
    op.create_index(
        op.f("ix_exercises_deleted_at"), "exercises", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_exercises_position"), "exercises", ["position"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exercises_position"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_deleted_at"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_table("media_files")
    # ### end Alembic commands ###
