"""student progress and listening journal

Revision ID: 0004_listening
Revises: 0003_exercises
Create Date: 2026-09-29 21:26:00.185090

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004_listening"
down_revision: str | Sequence[str] | None = "0003_exercises"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listening_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("audio_id", sa.String(length=36), nullable=False),
        sa.Column("exercise_title", sa.String(length=200), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_position_sec", sa.Float(), nullable=False),
        sa.Column("audio_duration_sec", sa.Float(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "audio_duration_sec > 0", name=op.f("ck_listening_sessions_duration")
        ),
        sa.CheckConstraint(
            "max_position_sec >= 0 AND max_position_sec <= audio_duration_sec",
            name=op.f("ck_listening_sessions_position"),
        ),
        sa.ForeignKeyConstraint(
            ["audio_id"],
            ["media_files.id"],
            name=op.f("fk_listening_sessions_audio_id_media_files"),
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_listening_sessions_exercise_id_exercises"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_listening_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listening_sessions")),
        sa.UniqueConstraint(
            "session_id", name=op.f("uq_listening_sessions_session_id")
        ),
    )
    op.create_index(
        op.f("ix_listening_sessions_exercise_id"),
        "listening_sessions",
        ["exercise_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_listening_sessions_started_at"),
        "listening_sessions",
        ["started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_listening_sessions_user_id"),
        "listening_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "student_progress",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("next_exercise_id", sa.Integer(), nullable=True),
        sa.Column("last_random_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["last_random_id"],
            ["exercises.id"],
            name=op.f("fk_student_progress_last_random_id_exercises"),
        ),
        sa.ForeignKeyConstraint(
            ["next_exercise_id"],
            ["exercises.id"],
            name=op.f("fk_student_progress_next_exercise_id_exercises"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_student_progress_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_student_progress")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_progress")
    op.drop_index(
        op.f("ix_listening_sessions_user_id"), table_name="listening_sessions"
    )
    op.drop_index(
        op.f("ix_listening_sessions_started_at"), table_name="listening_sessions"
    )
    op.drop_index(
        op.f("ix_listening_sessions_exercise_id"), table_name="listening_sessions"
    )
    op.drop_table("listening_sessions")
    # ### end Alembic commands ###
