"""telegram linking imports and worker state

Revision ID: 0005_telegram
Revises: 0004_listening
Create Date: 2026-09-29 22:59:08.291651

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005_telegram"
down_revision: str | Sequence[str] | None = "0004_listening"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_state",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("next_offset", sa.BigInteger(), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_state")),
    )
    op.create_table(
        "telegram_link_codes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_telegram_link_codes_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_telegram_link_codes")),
        sa.UniqueConstraint(
            "token_hash", name=op.f("uq_telegram_link_codes_token_hash")
        ),
    )
    op.create_table(
        "telegram_links",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_telegram_links_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_telegram_links")),
        sa.UniqueConstraint("sender_id", name=op.f("uq_telegram_links_sender_id")),
    )
    op.create_table(
        "telegram_updates",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("file_id", sa.String(length=512), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=64), nullable=True),
        sa.Column("media_id", sa.String(length=36), nullable=True),
        sa.Column("exercise_id", sa.Integer(), nullable=True),
        sa.Column("applied_request", sa.String(length=64), nullable=True),
        sa.Column("reply_code", sa.String(length=32), nullable=False),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('message','pending','ready','failed','applied','discarded')",
            name=op.f("ck_telegram_updates_status"),
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_telegram_updates_exercise_id_exercises"),
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media_files.id"],
            name=op.f("fk_telegram_updates_media_id_media_files"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_telegram_updates_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_updates")),
    )
    op.create_index(
        op.f("ix_telegram_updates_status"), "telegram_updates", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_telegram_updates_user_id"),
        "telegram_updates",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telegram_updates_user_id"), table_name="telegram_updates")
    op.drop_index(op.f("ix_telegram_updates_status"), table_name="telegram_updates")
    op.drop_table("telegram_updates")
    op.drop_table("telegram_links")
    op.drop_table("telegram_link_codes")
    op.drop_table("telegram_state")
    # ### end Alembic commands ###
